### ISSUE TITLE
Normal slash in path instead of backslash?

### ISSUE THREAD

**Issue by maxiey** [X-Necro-X/Icon-Extractor#1]
Does the code work for you as is? because windows uses backslashes in paths, so the .exe you supplied doesn't work.
Maybe I'm doing something wrong - I'm new to this.
I just yoinked your code and changed the slashes to backslashes (ln 10-11) and code works great! Many thanks!

**Comment by X-Necro-X** [comment]
Yes, it works fine for me. Glad it worked out for you.
